#!/bin/bash
export PYTHONPATH="$PYTHONPATH:$APPDIR/usr/lib/python3.9/site-packages"
# LD_LIBRARY_PATH="$APPDIR/usr/lib/x86_64-linux-gnu" $APPDIR/usr/bin/python3
"$APPDIR/usr/bin/nvim" -u "$APPDIR/.config/nvim/init.vim" "$@"
